*
* Bliss Environment Library , X680x0 Mercury Programming Interface Definition
*
* for MercuryDriver Version 0.86 after
*

		.nlist

MERC	macro	CallNumber
	moveq.l	#CallNumber,d1
	moveq.l	#$F4,d0
	trap	#$0F
	endm

_M_IOCS		equ	-1

_PCMOUT		equ	$00
_PCMAOUT	equ	$02
_PCMSNS		equ	$06
_PCMMOD		equ	$07
_MUSTAT		equ	$08

_OPNSET		equ	$0A
_OPNSNS		equ	$0B
_OPNINTST	equ	$0C

_START		equ	$0E
_STOP		equ	$0F

		.list
